# Railway deployment configuration for BitterBot Admin Backend

[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.admin"

[deploy]
startCommand = "python -m admin_console.server"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[[services]]
name = "admin-gateway"
port = 8000
handlers = ["http", "websocket"]

[[services]]
name = "engram-service" 
port = 8080
internalOnly = true

[[services]]
name = "metrics-aggregator"
port = 8081
internalOnly = true

[environment]
ADMIN_CONSOLE_ENABLED = "true"
CORS_ORIGINS = "https://bitterbot-admin.vercel.app"
METRICS_RETENTION_DAYS = "30"
LOG_LEVEL = "INFO"
ENABLE_ACADEMIC_MODE = "true"

# Database
DATABASE_POOL_SIZE = "20"
DATABASE_MAX_OVERFLOW = "10"

# Security
ADMIN_API_KEY = "${{ secrets.ADMIN_API_KEY }}"
JWT_SECRET = "${{ secrets.JWT_SECRET }}"

# Feature flags
ENABLE_ENGRAM_MODULE = "true"
ENABLE_P2P_MODULE = "false"
ENABLE_FL_MODULE = "false"

# Monitoring
SENTRY_DSN = "${{ secrets.SENTRY_DSN }}"
PROMETHEUS_ENABLED = "true"